# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\bmswin.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(593, 377)
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 20, 511, 331))
        self.widget.setStyleSheet("background-color: rgba(255, 255, 255, 200);\n"
"border-radius:30px")
        self.widget.setObjectName("widget")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(480, 10, 21, 20))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/Close-256.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 161, 331))
        self.widget_2.setStyleSheet("background-color: rgba(255, 252, 237, 210);")
        self.widget_2.setObjectName("widget_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 70, 111, 41))
        self.pushButton_6.setStyleSheet("background-color: rgba(255, 237, 143, 220);\n"
"font: 75 16pt \"微软雅黑\";\n"
"border-radius:10px;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 130, 111, 41))
        self.pushButton_7.setStyleSheet("background-color: rgba(255, 237, 143, 220);\n"
"font: 75 16pt \"微软雅黑\";\n"
"border-radius:10px;")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 190, 111, 41))
        self.pushButton_8.setStyleSheet("background-color: rgba(255, 237, 143, 220);\n"
"font: 75 16pt \"微软雅黑\";\n"
"border-radius:10px;")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_9.setGeometry(QtCore.QRect(20, 250, 111, 41))
        self.pushButton_9.setStyleSheet("background-color: rgba(255, 237, 143, 220);\n"
"font: 75 16pt \"微软雅黑\";\n"
"border-radius:10px;")
        self.pushButton_9.setObjectName("pushButton_9")
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget)
        self.stackedWidget.setGeometry(QtCore.QRect(160, 50, 341, 271))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 30, 171, 31))
        self.lineEdit_2.setStyleSheet("border-radius:8px;\n"
"border:1px solid rgb(255, 239, 156)")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.page)
        self.pushButton_4.setGeometry(QtCore.QRect(80, 200, 171, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgba(255, 239, 156, 220);\n"
"border-radius:8px")
        self.pushButton_4.setObjectName("pushButton_4")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_6.setGeometry(QtCore.QRect(80, 70, 171, 31))
        self.lineEdit_6.setStyleSheet("border-radius:8px;\n"
"border:1px solid rgb(255, 239, 156)")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_7.setGeometry(QtCore.QRect(80, 110, 171, 31))
        self.lineEdit_7.setStyleSheet("border-radius:8px;\n"
"border:1px solid rgb(255, 239, 156)")
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_8.setGeometry(QtCore.QRect(80, 150, 171, 31))
        self.lineEdit_8.setStyleSheet("border-radius:8px;\n"
"border:1px solid rgb(255, 239, 156)")
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.lineEdit = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit.setGeometry(QtCore.QRect(30, 30, 171, 31))
        self.lineEdit.setStyleSheet("border-radius:8px;\n"
"border:1px solid rgb(255, 239, 156)")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 30, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgba(255, 239, 156, 220);\n"
"border-radius:8px")
        self.pushButton_2.setObjectName("pushButton_2")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_9.setGeometry(QtCore.QRect(30, 30, 171, 31))
        self.lineEdit_9.setStyleSheet("border-radius:8px;\n"
"border:1px solid rgb(255, 239, 156)")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_3.setGeometry(QtCore.QRect(230, 30, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgba(255, 239, 156, 220);\n"
"border-radius:8px")
        self.pushButton_3.setObjectName("pushButton_3")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_3.setGeometry(QtCore.QRect(90, 60, 171, 31))
        self.lineEdit_3.setStyleSheet("border-radius:8px;\n"
"border:1px solid rgb(255, 239, 156)")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_3.setCursorPosition(0)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_4.setGeometry(QtCore.QRect(90, 110, 171, 31))
        self.lineEdit_4.setStyleSheet("border-radius:8px;\n"
"border:1px solid rgb(255, 239, 156)")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_5.setGeometry(QtCore.QRect(90, 160, 171, 31))
        self.lineEdit_5.setStyleSheet("border-radius:8px;\n"
"border:1px solid rgb(255, 239, 156)")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_5.setGeometry(QtCore.QRect(90, 210, 171, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgba(255, 239, 156, 220);\n"
"border-radius:8px")
        self.pushButton_5.setObjectName("pushButton_5")
        self.stackedWidget.addWidget(self.page_4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_6.setText(_translate("MainWindow", "添加图书"))
        self.pushButton_7.setText(_translate("MainWindow", "删除图书"))
        self.pushButton_8.setText(_translate("MainWindow", "查找图书"))
        self.pushButton_9.setText(_translate("MainWindow", "修改密码"))

        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "书名："))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "作者："))
        self.lineEdit_7.setPlaceholderText(_translate("MainWindow", "数量："))
        self.lineEdit_8.setPlaceholderText(_translate("MainWindow", "地址："))
        self.pushButton_4.setText(_translate("MainWindow", "确认添加"))

        self.lineEdit.setPlaceholderText(_translate("MainWindow", "书名："))
        self.pushButton_2.setText(_translate("MainWindow", "删除"))

        self.lineEdit_9.setPlaceholderText(_translate("MainWindow", "书名："))
        self.pushButton_3.setText(_translate("MainWindow", "查找"))
        
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "旧密码："))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "新密码："))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "确认密码："))
        self.pushButton_5.setText(_translate("MainWindow", "确认修改"))
import win.resource_rc as resource_rc
